# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Windsorcli < Formula
  desc "The Windsor Command Line Interface"
  homepage "https://windsorcli.github.io"
  version "0.0.47"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/tvangundy/cli/releases/download/v0.0.47/windsorcli_0.0.47_darwin_arm64.tar.gz"
    sha256 "50a8ac86b0219bca7209a2c7aa5229174938385fcf577bb3049b08fb954de2e5"

    def install
      bin.install "windsorcli"
    end
  end
end
