# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Windsorcli < Formula
  desc ""
  homepage ""
  version "0.0.46"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/tvangundy/cli/releases/download/v0.0.46/windsorcli_0.0.46_darwin_arm64.tar.gz"
    sha256 "17a4f417127b832a62722f0173402962153f10d3a24c7521e069352b700471d6"

    def install
      bin.install "windsorcli"
    end
  end
end
