# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Windsor < Formula
  desc "The Windsor Command Line Interface"
  homepage "https://windsorcli.github.io"
  version "0.0.48"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/tvangundy/cli/releases/download/v0.0.48/windsorcli_0.0.48_darwin_arm64.tar.gz"
    sha256 "43f06a84461788aea550ada86f8fd7a28532dec28664d49364712d1ce031c030"

    def install
      bin.install "windsorcli"
    end
  end
end
