# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Windsorcli0049DarwinArm64 < Formula
  desc "The Windsor Command Line Interface"
  homepage "https://windsorcli.github.io"
  version "0.0.50"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/tvangundy/cli/releases/download/v0.0.50/windsorcli_0.0.50_darwin_arm64.tar.gz"
    sha256 "2ec05efb5eae54b735d8603e8a3a14392a983fc5a0268cac368334d1eaf8a9ab"

    def install
      bin.install "windsorcli"
    end
  end
end
